### ISSUE TITLE
What to add to Options and what to add to the popup under extension icon?

### ISSUE THREAD

**Issue by FifthRooter** [FifthRooter/pop-boy-3000#23]
I'm not sure how to go about populating both of these elements.
Currently it seems that most if not all of the possible configurable options would fit in the options popup, so there would be very little use for the Options page.

My suggestion would be to focus on populating the options popup with configurations, and leaving the Options page empty for the time being, and later perhaps simply copying the content of the popup into the Options page + adding some additional info/documentation perhaps.

**Comment by emilsbee** [comment]
I think you can definitely just disable the Options page completely. Most if not all extensions that I have don't have the Options page. Even a big extension like Bitwarden doesn't have an Options page.

**Comment by FifthRooter** [comment]
Good point, that's the way.
